version: '3'
services:
  my-frontend-app:
#    build:
#      context: ./
#      dockerfile: Dockerfile
    image: ${DOCKER_REGISTRY}/${APP_NAME}:${TAG_VERSION}
    ports:
      - "3000:3000"
    env_file: .env
  mongodb:
    image: mongo
    ports:
     - "27017:27017"
    env_file: .env
    volumes:
     - mongo-data:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    ports:
     - "8081:8081"
    env_file: .env
    depends_on:
     - "mongodb"
volumes:
  mongo-data:
    driver: local
